from decouple import config

TRAINING_ANNOTATIONS_PATH = config("TRAINING_ANNOTATIONS_PATH")
VALIDATION_ANNOTATIONS_PATH = config("VALIDATION_ANNOTATIONS_PATH")

TRAINING_IMAGES_FOLDER = config("TRAINING_IMAGES_FOLDER")
VALIDATION_IMAGES_FOLDER = config("VALIDATION_IMAGES_FOLDER")

MODELS_SAVE_LOCATION = config("MODELS_SAVE_LOCATION")
LOGS_SAVE_LOCATION = config("LOGS_SAVE_LOCATION")

DEVICE = config("DEVICE")
EPOCHS = int(config("EPOCHS"))
BATCH_SIZE = int(config("BATCH_SIZE"))
LOAD_MODEL = True
NUMBER_OF_WORDS_FOR_VOCABULARY = int(config("NUMBER_OF_WORDS_FOR_VOCABULARY"))
DISCORD_TOKEN = config("DISCORD_TOKEN")

EMBEDDING_SIZE = int(config("EMBEDDING_SIZE"))
HIDDEN_SIZE = int(config("HIDDEN_SIZE"))
GRU_LAYERS = int(config("GRU_LAYERS"))
LEARNING_RATE = float(config("LEARNING_RATE"))

PADDING_INDEX = 3

TEMP_PATH = config("TEMP_PATH")
